export const GET_CAPTCHA_ID = 'GET_CAPTCHA_ID';

export const SHOW_MSG = 'SHOW_MSG';
export const HIDE_MSG = 'HIDE_MSG';

export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';

export const USERINFO_SUCCESS = 'USERINFO_SUCCESS';
export const USERINFO_FAILURE = 'USERINFO_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const AUTH_UPLOAD_AVATAR_SUCCESS = 'AUTH_UPLOAD_AVATAR_SUCCESS';

export const GET_NODES_SUCCESS = 'GET_NODES_SUCCESS';
export const GET_NODES_LAST_TOPICS_SUCCESS = 'GET_NODES_LAST_TOPICS_SUCCESS';

export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';

export const REGISTER_BUTTON_TURE = 'REGISTER_BUTTON_TURE';
export const REGISTER_BUTTON_FALSE = 'REGISTER_BUTTON_FALSE';

export const GET_PLATFORM_SUCCESS = 'GET_PLATFORM_SUCCESS';

export const GET_GAMESTYLE_SUCCESS = 'GET_GAMESTYLE_SUCCESS';

export const RELEASE_TOPIC_BUTTON_SUCCESS = 'RELEASE_TOPIC_BUTTON_SUCCESS';
export const RELEASE_TOPIC_BUTTON_FIL = 'RELEASE_TOPIC_BUTTON_FIL';
export const GET_RANK_TOPICS_SUCCESS = 'GET_RANK_TOPICS_SUCCESS';
export const HOME_MENU_TOPIC_LOADING_TRUE = 'HOME_MENU_TOPIC_LOADING_TRUE';
export const HOME_MENU_TOPIC_LOADING_FALSE = 'HOME_MENU_TOPIC_LOADING_FALSE';

export const GET_TOPIC_SUCCESS = 'GET_TOPIC_SUCCESS';
export const SAVE_TOPIC_REPLY_SUCCESS = 'SAVE_TOPIC_REPLY_SUCCESS';
export const RELEASE_REPLY_BUTTON_SUCCESS = 'RELEASE_REPLY_BUTTON_SUCCESS';
export const RELEASE_REPLY_BUTTON_FIL = 'RELEASE_REPLY_BUTTON_FIL';

export const UP_TOPIC_REPLY_SUCCESS = 'UP_TOPIC_REPLY_SUCCESS';
export const UP_TOPIC_RANK = 'UP_TOPIC_RANK';

export const GET_ADMIN_POSTS_SUCCESS = 'GET_ADMIN_POSTS_SUCCESS';
export const ADMIN_DEL_TOPIC_SUCCESS = 'ADMIN_DEL_TOPIC_SUCCESS';
